#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.
# shellcheck disable=SC2086

domain_information () {
    local domain=$1
    local subdomain=$2
    local line=$(dig "$subdomain"."$domain" +short | tr '\t' '\n')
    local record_type="A"
    if [[ "$line" == *"CNAME"* ]]; then
        record_type="CNAME"
    fi
    echo "$subdomain $line" | awk -v rt="$record_type" '{print "The subdomain " $1 " is a " rt " record and points to " $2}'
}

if [ "$#" -eq 1 ]; then
  domain_information "$1" "www"
  domain_information "$1" "lb-01"
  domain_information "$1" "web-01"
  domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]; then
  domain_information "$1" "$2"
else
  echo "Usage: $0 <domain> [subdomain]"
fi
