#!/usr/bin/env bash
# script displays information about subdomains


display_dns_info() {
    subdomain="$1"
    domain="$2"
    result=$(dig "$subdomain"."$domain" | awk '/^'"${subdomain}"'\./ {print $5}')
    echo "The subdomain $subdomain is a A record and points to $result"
}

if [ $# -eq 0 ]; then
    echo "Error: Missing domain argument"
    exit 1
fi

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
    display_dns_info "$sub" "$domain"
done

