#!/usr/bin/env bash
# Install HAproxy if it's not already installed
if ! command -v haproxy &> /dev/null; then
  sudo apt-get update
  sudo apt-get install -y haproxy
fi

sudo systemctl enable haproxy

CONFIG="\
global
  log /dev/log local0
  log /dev/log local1 notice
  chroot /var/lib/haproxy
  stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
  stats timeout 30s
  user haproxy
  group haproxy
  daemon

defaults
  log global
  option httplog
  option dontlognull
  timeout connect 10s
  timeout client 60s
  timeout server 60s

frontend httpandhttps
  bind *:80
  bind *:443 ssl crt /home/ubuntu/haproxy.pem
  mode http
  http-request redirect scheme https code 301 unless { ssl_fc }
  stats uri /haproxy?stats
  default_backend http_back

backend http_back
  mode http
  balance roundrobin
  server web-01 35.153.67.248:80 check 
  server web-02 52.3.248.109:80 check
"

echo "$CONFIG" | sudo tee /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
