#!/usr/bin/env bash
# Ignore SC2154 for shellcheck
# shellcheck disable=SC2154

sudo apt-get update

if ! dpkg -l | grep -q nginx; then
    sudo apt-get install -y nginx
fi

HOSTNAME=$(hostname)

if ! grep -q "add_header X-Served-By" /etc/nginx/conf.d/default.conf; then
    echo "add_header X-Served-By $HOSTNAME;" | sudo tee -a /etc/nginx/conf.d/default.conf
fi

sudo nginx -t
sudo service nginx restart
