#!/usr/bin/env bash
# This is a Bash script that displays a list of currently running processes and
# shows all processes, for all users, including those which might not have a TTY
# displays in a user-oriented format and
# shows process hierarchy


ps aux --forest
