#!/usr/bin/env bash
# This is a Bash script that displays the PID, along with the process name, of processes whose name contain the word "bash".

bash_pids=$(pgrep -f bash)

for pid in $bash_pids; do
    echo "$pid bash"
done
