#!/usr/bin/env bash
#This is a Bash script that uses "kill" to stop 4-to_infinity_and_beyond process.

pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -z "$pid" ]; then
    echo "Process not found."
else
    kill -15 "$pid"
    echo "Terminated."
fi
