#!/usr/bin/env bash
# This is  a Bash script that displays:
# "To infinity and beyond" indefinitely, with a sleep 2 in between each iteration
# "I am invincible!!!"" when receiving a SIGTERM signal

until false; do
    echo "To infinity and beyond"
    sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
