#!/usr/bin/env bash
# This is a while loop with a nested if construct that prints "Best School" and "hi".

num=1
while [ $num -le 10 ]
do
	echo "Best School"
if [ $num -eq 9 ]
then
	echo "Hi"
fi
	num=$(( num +1  ))
done
