#!/usr/bin/env bash
# This a Bash script that loops from 1 to 10 and displays 4 and then bad luck from China for the 4th loop iteration, 9 and then bad luck from Japan for the 9th loop iteration, and 17 and then bad luck from Italy for the 17th loop iteration.
num=1
while [ $num -le 20 ]
do

if [ $num -eq 4 ]; then
	echo "$num" && echo "bad luck from China"
elif [ $num -eq 9 ]; then
	echo "$num" && echo "bad luck from Japan"
elif [ $num -eq 17 ]; then
	echo "$num" && echo "bad luck from Italy"
else
	echo "$num"
fi
	num=$(( num +1 ))
done
