#!/usr/bin/env bash
#  This is a Bash script that displays the time for 12 hours and 59 minutes, displaying hours from 0 to 12 and minutes from 1 to 59.

hour=0
while [ $hour -le 12 ]
do
	minute=1
	echo "Hour: $hour"
	while [ $minute -le 59 ]
	do
		echo "$minute"
		minute=$(( minute +1 ))
	done

	hour=$(( hour +1  ))
done
