#!/bin/env bash
# This  a Bash script that displays content of current directory in list format where only part of name after first dash is displayed
for file in *; do
    if [[ $file != .* ]]; then

        name_after_dash=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name_after_dash"
    fi
done
